### ISSUE TITLE
Add catRecord usage examples

### ISSUE THREAD

**Issue by nikolasleblanc** [rangle/typed-immutable-record#10]
Just to drive the point home, show some record-y usages of catRecord after it's been created.

**Comment by danielfigueiredo** [comment]
Alright, that makes sense. Would help people to understand that they're dealing with an Immutable.map that you can also dot access any property defined in your <E> interface.
I wonder whether explaining what is <T> and <E> somewhere in the README.md wouldn't also be helpful

**Comment by nikolasleblanc** [comment]
Yeah, that's what I mean, at the end of your readme, before recordify, where you show to get catRecord from the AnimalFactory, show usage examples of that catRecord along with comments explaining the record-y functionality being employed. So, dot access, using .set, removing a property and showing how it's been set to its default value.
