### ISSUE TITLE
I'm getting warning message

### ISSUE THREAD

**Issue by jean-merelis** [rangle/typed-immutable-record#11]
I'm getting this warning

WARNING in ./~/typed-immutable-record/dist/src/typed.factory.js
Cannot find source file '../../src/typed.factory.ts': Error: Cannot resolve 'file' or 'directory' ../../src/typed.factory.ts in /home/jean/projects/lab/myproject/node_modules/typed-immutable-record/dist/src

installed via npm. version 0.0.3

My imports
```javascript 
import { TypedRecord, makeTypedFactory } from 'typed-immutable-record';
```

What can it be?

**Comment by danielfigueiredo** [comment]
Let me check this and I will get back to you

**Comment by danielfigueiredo** [comment]
Alright so it looks like the reason is because npmignore was missing few things and it was bringing in files it shouldn't.
I will create a PR and publish it again

**Comment by danielfigueiredo** [comment]
New version 0.0.4 was published, please let me know if everything is fine so I can close this issue.

**Comment by jean-merelis** [comment]
I'm getting these warnings now

WARNING in ./~/typed-immutable-record/dist/index.js
Cannot find source file '../index.ts': Error: Cannot resolve 'file' or 'directory' ../index.ts in /home/jean/projects/lab/myproject/node_modules/typed-immutable-record/dist

WARNING in ./~/typed-immutable-record/dist/src/typed.factory.js
Cannot find source file '../../src/typed.factory.ts': Error: Cannot resolve 'file' or 'directory' ../../src/typed.factory.ts in /home/jean/projects/lab/myproject/node_modules/typed-immutable-record/dist/src

v0.0.4

**Comment by danielfigueiredo** [comment]
could you please push this code into some repo that I can checkout?
I've included it in other projects I get no errors / warnings

**Comment by jean-merelis** [comment]
It persists yet. It looks issues with source map.

**Comment by danielfigueiredo** [comment]
If you delete all source maps from inside node_modules/typed-immutable-record does the warning go away? I think I we don't really need them in the npm package

**Comment by jean-merelis** [comment]
excluding all source maps from within node_modules/typed-immutable-record and all reference within js files the warnings go away

**Comment by danielfigueiredo** [comment]
Great, I know how to fix that now. Will do it again, thanks for the feedback

**Comment by danielfigueiredo** [comment]
@jean-merelis I removed the source maps option from the tsconfig, and it of course kills the generated .map files and also removes the references from within the js files.
I also updating the docs regarding others open issues and will publish a new version after that.
The PR that will fix is https://github.com/rangle/typed-immutable-record/pull/14

thanks

**Comment by jean-merelis** [comment]
I thank you.
You are doing a great job in this lib

**Comment by danielfigueiredo** [comment]
Version 0.0.5 is published. Let me know if your warning are finally gone now =]

**Comment by jean-merelis** [comment]
It is ok now. Thanks.
