### ISSUE TITLE
Extra generic argument <E> on TypedRecord interface

### ISSUE THREAD

**Issue by danielfigueiredo** [rangle/typed-immutable-record#16]
Recently I've been hearing about cases where we could use the interface `<E>` that describes the shape of the model, such as `IAnimal` type in README.md examples.
If the TypedRecord knows about the `<E>` type, it could also change the return type and arguments for few functions.
`toJS()` could return `<E>` instead of any, which is for sure a valid use case.
Functions that gets a plain JS object as arguments to perform operations in the Immutable.Record also could restrict that type to `<E>`, in other words any object that is `IAnimal` for example, not `IAnimalRecord`. An example would be the `merge` function:

``` typescript
    merge(...iterables: Iterable<K, V>[]): Map<K, V>;
    merge(...iterables: {[key: string]: V}[]): Map<string, V>;
```

`mergeDeep` also another candidate. 
The disadvantages of this approach is that you would need to provide all required attributes in your interface, it can be annoying to perform operations where you just want to merge a small part of `<E>`. For that I thought about making the signature something like:

``` typescript
merge<E extends T>(obj: T);
```

If that is somehow possible without the compiler yelling at me.
I'm pretty sure looking deep at it we might find other functions that would make the TypedRecord more restrict considering the model `<E>`.

Another downside to keep in mind is that the syntax for declaring the interface would be:

```
interface IAnimalRecord extends TypedRecord<IAnimalRecord, IAnimal>, IAnimal {}
```

It's getting uglier but might be worth doing, not sure at this point.

Does anyone have any thoughts on this?
@SethDavenport @clbond @bennett000

**Comment by bennett000** [comment]
@danielfigueiredo have you been reading up on what's coming in Typescript > 2.0.0?

**Comment by danielfigueiredo** [comment]
Alright, I've played around with this and the problem is typescript limitation in order to make this really cool
I created this branch that changed the TypedRecord to also receive `E` as an argument
https://github.com/danielfigueiredo/typed-immutable-record/blob/feat-strongly-typed-objs/src/typed.record.ts
The problem is that you'd have to define your properties with a `?`, so that you could do partial updates in the `E` type
other benefits such as toJS returning `E` is also working
When [this](https://github.com/Microsoft/TypeScript/issues/4889) thread gets resolved, we could make all updater methods like
```typescript
merge<A super E>(obj: A);
```
so that any object send must have properties define in `E` but not have all the properties

**Comment by danielfigueiredo** [comment]
Having said that, I'm not sure if it worth publishing a new version with these changes
Might be good for few people might not be good for another, I wouldn't like to restrict whoever is using this to now have to change the interfaces and mark all properties with `?` because Typescript is lacking a feature.
@clbond you had a use case where you wanted these strongly typed objects in immutable operations, let me know if you have any ideas about this
