### ISSUE TITLE
Create functionality to automatically execute factory function on a declared type when .merge() is called

### ISSUE THREAD

**Issue by egervari** [rangle/typed-immutable-record#17]
Thanks so much for creating this small library. It is really cool to work with strongly-typed immutable things rather than typeless maps/objects.

One of the pain points for someone new to the library has to do with expectations of how the redux states are constructed and merged. Having to manually call the factory method every time we build a state from anywhere in the application, the application developer has to be aware of the inner details of that proper state construction. So instead of simply creating an object that represents a type, they have to create a factory and run the factory instead.

This manual factory creation results in a lot of duplication in all of the reducers and anywhere else where state is modified, and it can be especially painful when you have deeply nested state object graphs. A simpler approach would be to let the user construct plain TypeScript objects, and have the details of the factory construction be handled automatically. We can do this 'magic' by specifying the relationship between declared types and factories. So when we call `.merge()`, we could check the type of the property, and if it has a factory defined for that type, we could wrap the value with the factory. This adds a lot of clarity and simplicity to using the library, and removes a lot of unnecessary duplication where a factory is called in many places in the application.

This change will also make our applications more robust, because there is zero chance a developer could accidentally forget to wrap a typed object with a factory call.

**Comment by danielfigueiredo** [comment]
Yes, this is a problem we're facing when using Immutable.Records, I found this https://github.com/facebook/immutable-js/issues/385 on Immutablejs repo
A facebook member said 
"What I believe you're referring to here is a way to parse a nested JS object into nested Records. The Record constructors will not do this for you, as it is equally valid to provide a regular JS object as a key. Instead, you should use Immutable.fromJS() with a custom reviver function which is written in a way that relates to your data schema."
Maybe what we are looking for a an easy way to create a reviver function to correlate our data schema. I haven't heard about revive functions yet, but I will look into this

**Comment by danielfigueiredo** [comment]
Playing around with this if we have a way to specify the shape of our record tree, we would be able to write a generic reviver that could handle the work for us in a fromJS call
I wrote a stupid test case that illustrates the scenario
```typescript
    it('should generate records fromJS', () => {
      const ArtooFactory = makeTypedFactory<IPet, IPetRecord>({
        name: 'Artoo',
        type: 'Droid'
      });
      const LukeRecordFactory = makeTypedFactory<IPerson, IPersonRecord>({
        name: 'Luke',
        pet: ArtooFactory()
      });
      const FactoryMap = {
        root: {
          useFactory: LukeRecordFactory,
          pet: {
            useFactory: ArtooFactory
          }
        }
      };
      const root = FactoryMap.root;
      console.log('final', fromJS({
        name: 'Han solo',
        pet: {
          name: 'Chewbacca',
          type: 'Wookie'
        }
      }, function (key, val: any) {
        if (key !== '') {
          return root[key].factory(val);
        } else {
          return root.factory(val);
        }
      }));
```
the output gotten from this function is
```
final Record { "name": "Han solo", "pet": Record { "name": "Chewbacca", "type": "Wookie" } }
```
@mhazy
